### ISSUE TITLE
Milestone 2 Feedback (Pilot studies)

### ISSUE THREAD

**Issue by bxie** [info370/project-dataseyance#3]
Yes! I applaud you all for trying to inform some tough decisions.
This kind of work can have really important impact and that's exciting.

Some ways to further focus your thinking:
- who are the stakeholders who want to inform? Focusing on informing citizens vs businesses vs city officials (for example) changes your study.
- what do you want to optimize?

(no further action is required for this "issue" and you can close it after you've reviewed it)

**Comment by greglnelson** [comment]
HALA:
“How big is the surplus of land? Is this initiative worth the effort?”
Great uncertainty that was not addressed in the pilot study. Do a back of the envelope calculation. Or find out large it would need to be to make a difference.

It sounds like your decision has been scoped as “What land should be sold, for how much, 
does prior research suggest we will find something actionable from analysis?

How does the quantity of affordable housing affect other parts of the rental/housing market?
	try to estimate effects using order of magnitude / back of the envelope calculations. For example, if all the land owned is turned into affordable housing, what would the effect be?

What kinds of findings might our analysis yield and how would those inform decisions? Would that information make a difference? If not, what analysis might?

How do you validate z-estimate (or other valuation measures/services)?

Nalaxone:
I think that project is a PhD dissertation in social science to answer that question, requiring careful statistical models to deal with confounding factors. If you want a healthcare scenario, I can give you a juicy one.
